[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --themesDir=../.. --baseURL /"

[build.environment]
HUGO_VERSION = "0.79.1"
HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.79.1"

[context.deploy-preview]
command = "make prepare && hugo --source demo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_VERSION = "0.79.1"
