baseurl = "https://ruan.dev"
title = "Ruan Bekker"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "sysadminsblog"
googleAnalytics = "UA-200848025-1"

[params]
    author = "Ruan Bekker"
    description = "Ruan Bekker's Portfolio Website"
    keywords = "blog,devops,personal"
    info = "DevOps Engineer and Open Source Enthusiast"
    #avatarurl = "images/avatar.jpg"
    gravatar = "ruan@ruanbekker.com"
    footercontent = "Work Hard. Stay Humble. Be Kind."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/ruanbekker/ruan-dot-dev/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "GMQEJ"
#    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "ruan-dot-dev.analytics.ruan.dev"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/ruanbekker/"
[[params.social]]
    name = "Slack"
    icon = "fab fa-slack"
    weight = 2
    url = "http://linux-hackers-slack.herokuapp.com/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/ruanbekker/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/ruanbekker/"
[[params.social]]
    name = "Email"
    icon = "fas fa-at"
    weight = 5
    url = "mailto:ruan@ruanbekker.com"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://ruan.dev/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
[[params.social]]
    name = "Buy me a Coffee"
    icon = "fab fa-coffee"
    weight = 7
    url = "https://www.buymeacoffee.com/ruanbekker"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Crypto"
            weight = 4
            url = "crypto/"

            [[languages.en.menu.main]]
            name = "Resume"
            weight = 5
            url = "resume/"
            
            [[languages.en.menu.main]]
            name = "Appreciation"
            weight = 6
            url = "appreciation/"

            [[languages.en.menu.main]]
            name = "Shop"
            weight = 7
            url = "https://ko-fi.com/ruanbekker/shop"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 8
            url = "contact/"


#    [languages.af]
#        languagename = "Afrikaans"
#        title = "Ruan Bekker"

#        [languages.af.params]
#            author = "Ruan Bekker"
#            info = "DevOps"
#            description = "DevOps Ingenieur"
#            keywords = "blog,tegnologie,devops,persoonlik"
#            footercontent = "."

#        [languages.af.menu]

#            [[languages.af.menu.main]]
#            name = "About"
#            weight = 1
#            url = "about/"

#            [[languages.af.menu.main]]
#            name = "Blog"
#            weight = 2
#            url = "posts/"

#            [[languages.af.menu.main]]
#            name = "Projekte"
#            weight = 3
#            url = "projects/"

#            [[languages.af.menu.main]]
#            name = "Winkel"
#            weight = 4
#            url = "https://ko-fi.com/ruanbekker/shop"

#            [[languages.af.menu.main]]
#            name = "Kontak"
#            weight = 5
#            url = "contact/"
